#' @title cell_to_mod_cor
#' @description Calculates Spearman correlation between module scoring and cell log ratio.  Operates on "immune_cell_logratios" input to "run_ICLite"
#' @param score_mat A score matrix generated by mod_score_matrix_assembly.
#' @return A matrix of Spearman rho values
#' @export

cell_to_mod_cor<-function(score_mat){

  total_modules<-ncol(score_mat)
  cell_to_mod_mat<-matrix(ncol = ncol(score_mat), nrow = ncol(immune_cell_logratios))

  for(y in 1:total_modules){

    for(x in 1:ncol(immune_cell_logratios)){
      cell_to_mod_mat[x,y]<-cor.test(immune_cell_logratios[,x], score_mat[,y], method = "spearman")$estimate
    }
  }

  return(cell_to_mod_mat)

}
